### ISSUE TITLE
Can't build on Ubuntu 25.10

### ISSUE THREAD

**Issue by luispabon** [artizirk/wdisplays#32]
```
ninja: Entering directory `build'
[24/32] Generating resources/optimize-icon with a custom command
Scour processed file "../resources/wdisplays.svg" in 24 ms: 3851/21410 bytes new/orig -> 18.0%
[27/32] Compiling C object src/wdisplays.p/outputs.c.o
FAILED: src/wdisplays.p/outputs.c.o 
cc -Isrc/wdisplays.p -Isrc -I../src -Iresources -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/webp -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -pthread -MD -MQ src/wdisplays.p/outputs.c.o -MF src/wdisplays.p/outputs.c.o.d -o src/wdisplays.p/outputs.c.o -c ../src/outputs.c
../src/outputs.c:529:15: error: initialization of ‘void (*)(void *, struct zwlr_output_manager_v1 *)’ from incompatible pointer type ‘void (*)(void)’ [-Wincompatible-pointer-types]
  529 |   .finished = noop,
      |               ^~~~
../src/outputs.c:529:15: note: (near initialization for ‘output_manager_listener.finished’)
../src/outputs.c:31:13: note: ‘noop’ declared here
   31 | static void noop() {
      |             ^~~~
../src/outputs.c:556:20: error: initialization of ‘void (*)(void *, struct wl_registry *, uint32_t)’ {aka ‘void (*)(void *, struct wl_registry *, unsigned int)’} from incompatible pointer type ‘void (*)(void)’ [-Wincompatible-pointer-types]
  556 |   .global_remove = noop,
      |                    ^~~~
../src/outputs.c:556:20: note: (near initialization for ‘registry_listener.global_remove’)
../src/outputs.c:31:13: note: ‘noop’ declared here
   31 | static void noop() {
      |             ^~~~
../src/outputs.c:606:19: error: initialization of ‘void (*)(void *, struct zxdg_output_v1 *, int32_t,  int32_t)’ {aka ‘void (*)(void *, struct zxdg_output_v1 *, int,  int)’} from incompatible pointer type ‘void (*)(void)’ [-Wincompatible-pointer-types]
  606 |   .logical_size = noop,
      |                   ^~~~
../src/outputs.c:606:19: note: (near initialization for ‘output_listener.logical_size’)
../src/outputs.c:31:13: note: ‘noop’ declared here
   31 | static void noop() {
      |             ^~~~
../src/outputs.c:607:11: error: initialization of ‘void (*)(void *, struct zxdg_output_v1 *)’ from incompatible pointer type ‘void (*)(void)’ [-Wincompatible-pointer-types]
  607 |   .done = noop,
      |           ^~~~
../src/outputs.c:607:11: note: (near initialization for ‘output_listener.done’)
../src/outputs.c:31:13: note: ‘noop’ declared here
   31 | static void noop() {
      |             ^~~~
../src/outputs.c:609:18: error: initialization of ‘void (*)(void *, struct zxdg_output_v1 *, const char *)’ from incompatible pointer type ‘void (*)(void)’ [-Wincompatible-pointer-types]
  609 |   .description = noop
      |                  ^~~~
../src/outputs.c:609:18: note: (near initialization for ‘output_listener.description’)
../src/outputs.c:31:13: note: ‘noop’ declared here
   31 | static void noop() {
      |             ^~~~
[31/32] Compiling C object src/wdisplays.p/main.c.o
../src/main.c: In function ‘main’:
../src/main.c:1086:3: warning: ‘G_APPLICATION_FLAGS_NONE’ is deprecated: Use 'G_APPLICATION_DEFAULT_FLAGS' instead [-Wdeprecated-declarations]
 1086 |   GtkApplication *app = gtk_application_new(WDISPLAYS_APP_ID, G_APPLICATION_FLAGS_NONE);
      |   ^~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/giotypes.h:30,
                 from /usr/include/glib-2.0/gio/gio.h:28,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../src/main.c:4:
/usr/include/glib-2.0/gio/gioenums.h:1563:3: note: declared here
 1563 |   G_APPLICATION_FLAGS_NONE GIO_DEPRECATED_ENUMERATOR_IN_2_74_FOR(G_APPLICATION_DEFAULT_FLAGS),
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:270: meson-ninja-build] Error 1
make[1]: Leaving directory '/home/luis/Projects/sway_build'
make: *** [Makefile:311: wdisplays-build] Error 2
```

**Comment by JasonGantner** [comment]
It should have been fixed with artizirk#25 
Are you building an older version or are there other `noop` calls missing casts?

**Comment by luispabon** [comment]
Thank you Jason, it is indeed fixed now. There is are a couple of  remaining warnings, if you're interested. One during meson build, and another during ninja build:

```

~ ninja -C build
The Meson build system
Version: 1.9.1
Source dir: /home/luis/Projects/sway_build/wdisplays
Build dir: /home/luis/Projects/sway_build/wdisplays/build
Build type: native build
Project name: network.cycles.wdisplays
Project version: 1.1.3
C compiler for the host machine: cc (gcc 15.2.0 "cc (Ubuntu 15.2.0-4ubuntu4) 15.2.0")
C linker for the host machine: cc ld.bfd 2.45
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
Run-time dependency wayland-client found: YES 1.24.0
Run-time dependency wayland-protocols found: YES 1.45
protocol/meson.build:8: WARNING: Project does not target a minimum version but uses feature deprecated since '0.56.0': dependency.get_pkgconfig_variable. use dependency.get_variable(pkgconfig : ...) instead
Configuring resources.xml using configuration
Build-time dependency gio-2.0 found: YES 2.86.0
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program scour found: YES (/usr/bin/scour)
Configuring network.cycles.wdisplays.desktop using configuration
Library m found: YES
Library rt found: YES
Run-time dependency gdk-3.0 found: YES 3.24.50
Run-time dependency gtk+-3.0 found: YES 3.24.50
src/meson.build:9: WARNING: Project does not target a minimum version but uses feature deprecated since '0.56.0': dependency.get_pkgconfig_variable. use dependency.get_variable(pkgconfig : ...) instead
Run-time dependency epoxy found: YES 1.5.10
Configuring config.h using configuration
Build targets in project: 5
WARNING: Deprecated features used:
 * 0.56.0: {'dependency.get_pkgconfig_variable'}

Found ninja-1.13.0.git.kitware.jobserver-pipe-1 at /usr/local/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

~ sudo ninja -C build install
[24/32] Generating resources/optimize-icon with a custom command
Scour processed file "../resources/wdisplays.svg" in 15 ms: 3851/21410 bytes new/orig -> 18.0%
[30/32] Compiling C object src/wdisplays.p/main.c.o
../src/main.c: In function ‘main’:
../src/main.c:1087:3: warning: ‘G_APPLICATION_FLAGS_NONE’ is deprecated: Use 'G_APPLICATION_DEFAULT_FLAGS' instead [-Wdeprecated-declarations]
 1087 |   GtkApplication *app = gtk_application_new(WDISPLAYS_APP_ID, G_APPLICATION_FLAGS_NONE);
      |   ^~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/giotypes.h:30,
                 from /usr/include/glib-2.0/gio/gio.h:28,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../src/main.c:4:
/usr/include/glib-2.0/gio/gioenums.h:1563:3: note: declared here
 1563 |   G_APPLICATION_FLAGS_NONE GIO_DEPRECATED_ENUMERATOR_IN_2_74_FOR(G_APPLICATION_DEFAULT_FLAGS),
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
[32/32] Linking target src/wdisplays
ninja: Entering directory `build'
[0/1] Installing files
Installing resources/network.cycles.wdisplays.svg to /usr/local/share/icons/hicolor/scalable/apps
Installing src/wdisplays to /usr/local/bin
Installing /home/luis/Projects/sway_build/wdisplays/build/resources/network.cycles.wdisplays.desktop to /usr/local/share/applications
```

**Comment by JasonGantner** [comment]
I fixed those in my fork some time ago, I could make a PR if this repo becomes active again
